### Get all Pokemons
GET {{pokemonV1}}?pageSize=2&page=1
Content-Type: application/json

###

### GET pokemon by id
GET {{pokemonV1}}/920
Content-Type: application/json

###

### GET pokemon by name
GET {{pokemonV1}}/lokix
Content-Type: application/json

###

### GET pokemon by ids
GET {{pokemonV1}}/search/id?ids=1&ids=2
Content-Type: application/json

###

### GET pokemon by name
GET {{pokemonV1}}/search/name?search=bu&limit=3
Content-Type: application/json

###

### GET pokemon by generation
GET {{pokemonV1}}/search/generation?generation=generation-i
Content-Type: application/json

###

### GET file by id
GET {{pokemonV1}}/file/6796637dc816b9abf6e87d84

###
